# Generated by Django 4.1.7 on 2023-03-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='turkish_id',
            field=models.SmallIntegerField(default='1', max_length=11, verbose_name='Turkish ID number'),
        ),
    ]
