# Generated by Django 4.1.7 on 2023-03-05 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_turkish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='turkish_id',
            field=models.SmallIntegerField(default='1', verbose_name='Turkish ID number'),
        ),
    ]
