# Generated by Django 4.1.7 on 2023-03-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_passport_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='house_address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
