# Generated by Django 4.1.7 on 2023-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_house_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
