# Generated by Django 4.1.7 on 2023-03-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_car_plate_alter_user_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_car_model',
            field=models.CharField(blank=True, choices=[('genesis', 'GENESIS'), ('santafe', 'SANTAFE'), ('tucson', 'TUCSON'), ('elantra', 'ELANTRA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL'), ('won', 'WON')], max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('kr', 'Korean'), ('tr', 'Turkish'), ('en', 'English')], max_length=2),
        ),
    ]
