# Generated by Django 4.1.7 on 2023-03-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('ga', 'GA'), ('hr', 'HR'), ('pr', 'PR'), ('er', 'ER'), ('it', 'IT'), ('finance', 'FINANCE'), ('sales', 'SALES'), ('aftersales', 'AFTERSALES'), ('import', 'IMPORT'), ('export', 'EXPORT'), ('audit', 'AUDIT'), ('press', 'PRESS'), ('body', 'BODY'), ('paint', 'PAINT'), ('assembly', 'ASSEMBLY'), ('quality', 'QUALITY'), ('procurement', 'PROCUREMENT')], max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('ceo', 'CEO'), ('sales', 'SALES'), ('finance', 'FINANCE'), ('admin', 'ADMIN'), ('production', 'PRODUCTION'), ('procurement', 'PROCUREMENT')], max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='hq_position',
            field=models.CharField(blank=True, choices=[('sj', 'SJ'), ('bsj', 'BSJ'), ('jm', 'JM'), ('sm', 'SM'), ('cm', 'CM')], max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='is_expat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('ceo', 'CEO'), ('director', 'DIRECTOR'), ('coordinator', 'COORDINATOR')], max_length=15),
        ),
    ]
