# Generated by Django 4.1.7 on 2023-03-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cellphone_number',
            field=models.SmallIntegerField(default='1', verbose_name='Cellphone number'),
        ),
    ]
