# Generated by Django 4.1.7 on 2023-04-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_cellphone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_location',
            field=models.CharField(blank=True, choices=[('istanbul', 'Istanbul'), ('izmit', 'Izmit')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='car_model_year',
            field=models.SmallIntegerField(default='1', verbose_name='Car model year'),
        ),
    ]
