# Generated by Django 4.1.7 on 2023-04-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_car_location_user_car_model_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='house_location',
            field=models.CharField(blank=True, choices=[('alkent', 'Alkent'), ('sariyer', 'Sariyer'), ('besiktas', 'Besiktas'), ('gokturk', 'Gokturk')], max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_company_cars',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_driving_licenses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_family_residences',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_green_cards',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_houses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_moving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pick_ups',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_work_permits',
            field=models.BooleanField(default=False),
        ),
    ]
