# Generated by Django 4.1.7 on 2023-04-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_house_location_user_is_company_cars_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_family_residences',
            new_name='is_family_residence_permits',
        ),
    ]
