# Generated by Django 4.1.7 on 2023-06-25 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moving_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('arrival_location', models.CharField(default='', max_length=180)),
                ('pre_survey_date', models.DateField(default=datetime.date.today, verbose_name='Pre survey date')),
                ('pre_survey_time', models.TimeField(default='19:00', verbose_name='Pre survey time')),
                ('moving_start_date', models.DateField(default=datetime.date.today, verbose_name='Moving start date(Packing)')),
                ('moving_start_time', models.TimeField(default='19:00', verbose_name='Moving start time')),
                ('moving_finish_date', models.DateField(default=datetime.date.today, verbose_name='Moving finish date')),
                ('krsituation', models.CharField(blank=True, choices=[('domestic', '국내'), ('overseas', '해외')], max_length=150)),
                ('ensituation', models.CharField(blank=True, choices=[('domestic', 'Domestic'), ('overseas', 'Overseas')], max_length=150)),
                ('krstatus', models.CharField(blank=True, choices=[('request_submitted', '요청 제출됨'), ('checked', '총무팀 확인'), ('arranged', '이사업체 및 일정 어레인지 됨')], max_length=150)),
                ('enstatus', models.CharField(blank=True, choices=[('request_submitted', 'request submitted'), ('checked', 'GA team checked the request'), ('arranged', 'Moving company and schedule arranged')], max_length=150)),
                ('krreceiver', models.CharField(blank=True, choices=[('expat', '주재원'), ('spouse', '배우자')], max_length=150)),
                ('enreceiver', models.CharField(blank=True, choices=[('expat', 'Expat'), ('spouse', 'Spouse')], max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Moving requests',
            },
        ),
    ]
