# Generated by Django 4.1.7 on 2023-03-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moving_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moving_request',
            options={'verbose_name_plural': 'Moving requests'},
        ),
    ]
