# Generated by Django 4.1.7 on 2023-03-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_permits_requests', '0002_remove_work_permits_request_work_permit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work_permits_request',
            options={'verbose_name_plural': 'Work permits requests'},
        ),
    ]
