# Generated by Django 4.1.7 on 2023-03-13 21:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_residence_permits', '0002_rename_enstatus_family_residence_permit_enstatus_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family_residence_permits_preparation_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('expat_name', models.CharField(default='', max_length=180)),
                ('expat_birth_date', models.DateField(default=datetime.date.today, verbose_name='Expat birth date')),
                ('expat_id_number', models.CharField(default='', max_length=15)),
                ('expat_gender', models.CharField(default='', max_length=15)),
                ('spouse_name', models.CharField(default='', max_length=180)),
                ('spouse_birth_date', models.DateField(default=datetime.date.today, verbose_name='Spouse birth date')),
                ('spouse_id', models.CharField(default='', max_length=15)),
                ('spouse_gender', models.CharField(default='', max_length=15)),
                ('do_you_have_children', models.BooleanField(default=False)),
                ('marriage_certificate_address', models.CharField(default='', max_length=1000)),
                ('marriage_certificate_marriage_date', models.CharField(default='', max_length=180)),
                ('marriage_certificate_approved_date', models.CharField(default='', max_length=180)),
                ('marriage_certificate_approved_person', models.CharField(default='', max_length=180)),
                ('marriage_certificate_approved_place', models.CharField(default='', max_length=180)),
                ('marriage_certificate_document_date', models.DateField(default=datetime.date.today, verbose_name='Document date of Marriage certificate')),
                ('marriage_certificate_document_public_office', models.CharField(default='', max_length=180)),
                ('marriage_certificate_authorized_person', models.CharField(default='', max_length=180)),
                ('marriage_certificate_document_time', models.TimeField(default='19:00', verbose_name='Document time of Marriage certificate')),
                ('marriage_certificate_responsible_person', models.CharField(default='', max_length=180)),
                ('marriage_certificate_cellphone_number', models.CharField(default='', max_length=180)),
                ('marriage_certificate_person_who_request', models.CharField(default='', max_length=180)),
                ('marriage_certificate_document_number', models.CharField(default='', max_length=180)),
                ('criminal_record_address', models.CharField(default='', max_length=1000)),
                ('criminal_record_document_date', models.DateField(default=datetime.date.today, verbose_name='Document date of Criminal record certificate')),
                ('criminal_record_document_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Document time of Criminal record certificate')),
                ('criminal_record_person_who_request', models.CharField(default='', max_length=180)),
                ('criminal_record_document_number', models.CharField(default='', max_length=180)),
                ('national_police_service_address', models.CharField(default='', max_length=1000)),
                ('national_police_service_document_result', models.DateField(default=datetime.date.today, verbose_name='Document result date of National police service certificate')),
                ('national_police_service_consulate_result', models.DateField(default=datetime.date.today, verbose_name='consulate result date of National police service certificate')),
                ('national_police_service_official', models.CharField(default='', max_length=180)),
                ('national_police_service_authorized_official', models.CharField(default='', max_length=180)),
                ('national_police_service_document_number', models.CharField(default='', max_length=180)),
                ('child_name', models.CharField(default='', max_length=180)),
                ('child_birth_date', models.DateField(default=datetime.date.today, verbose_name='Child birth date')),
                ('child_id', models.CharField(default='', max_length=15)),
                ('child_gender', models.CharField(default='', max_length=15)),
                ('child_family_relations_certificate_address', models.CharField(default='', max_length=1000)),
                ('child_family_relations_certificate_document_date', models.DateField(default=datetime.date.today, verbose_name='Document date of child family relations certificate')),
                ('child_family_relations_certificate_document_public_office', models.CharField(default='', max_length=180)),
                ('child_family_relations_certificate_authorized_person', models.CharField(default='', max_length=180)),
                ('child_family_relations_certificate_document_time', models.TimeField(default='19:00', verbose_name='Document time of child family relations certificate')),
                ('child_family_relations_certificate_responsible_person', models.CharField(default='', max_length=180)),
                ('child_family_relations_certificate_cellphone_number', models.CharField(default='', max_length=180)),
                ('child_family_relations_certificate_person_who_request', models.CharField(default='', max_length=180)),
                ('child_family_relations_certificate_consulate_date', models.DateField(default=datetime.date.today, verbose_name='Document date of Consulate')),
                ('child_family_relations_certificate_document_number', models.CharField(default='', max_length=180)),
                ('endocument', models.CharField(blank=True, choices=[('power_of_attorney', 'Power of attorney'), ('cooperation_letter', 'Cooperation letter'), ('expat_family_relations_certificate', 'Expat Family relations certificate'), ('spouse_family_relations_certificate', 'Spouse Family relations certificate'), ('child1_family_relations_certificate', 'Child1 Family relations certificate'), ('child2_family_relations_certificate', 'Child2 Family relations certificate'), ('child3_family_relations_certificate', 'Child3 Family relations certificate'), ('child4_family_relations_certificate', 'Child4 Family relations certificate'), ('criminal_record_certificate', 'Criminal record certificate'), ('national_police_service', 'National police service'), ('marriage_certificate', 'Marriage certificate')], max_length=150)),
                ('expat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_residence_permits_preparation_documents', to=settings.AUTH_USER_MODEL)),
                ('residence_permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_residence_permits_preparation_documents', to='family_residence_permits.family_residence_permit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
