# Generated by Django 4.1.7 on 2023-06-25 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_residence_permits_preparation_documents', '0001_initial'),
        ('family_residence_permits', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='family_residence_permits_preparation_document',
            name='expat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_residence_permits_preparation_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='family_residence_permits_preparation_document',
            name='residence_permit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_residence_permits_preparation_documents', to='family_residence_permits.family_residence_permit'),
        ),
    ]
