# Generated by Django 4.1.7 on 2023-04-09 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('additional_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_information',
            name='responsible_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to=settings.AUTH_USER_MODEL),
        ),
    ]
