# Generated by Django 4.1.7 on 2023-03-09 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_residence_permits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family_residence_permit',
            old_name='Enstatus',
            new_name='enstatus',
        ),
        migrations.RenameField(
            model_name='family_residence_permit',
            old_name='Krstatus',
            new_name='krstatus',
        ),
        migrations.AddField(
            model_name='family_residence_permit',
            name='first_visit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='First visit date to Turkiye'),
        ),
        migrations.AlterField(
            model_name='family_residence_permit',
            name='passport_expiry_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Passport expiry date'),
        ),
    ]
