# Generated by Django 4.1.7 on 2023-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_residence_permits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_residence_permit',
            name='interview_place',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='family_residence_permit',
            name='post_office',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
