# Generated by Django 4.1.7 on 2023-03-14 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_residence_permits', '0003_document_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_residence_permit',
            name='interview_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Interview date'),
        ),
        migrations.AddField(
            model_name='family_residence_permit',
            name='interview_place',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='family_residence_permit',
            name='interview_time',
            field=models.TimeField(default='19:00', verbose_name='Interview time'),
        ),
    ]
