# Generated by Django 4.1.7 on 2023-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_residence_permits', '0004_family_residence_permit_interview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('detailed_information', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Visit places',
            },
        ),
        migrations.AddField(
            model_name='family_residence_permit',
            name='visit_place',
            field=models.ManyToManyField(related_name='family_residence_permits', to='family_residence_permits.visit_place'),
        ),
    ]
