# Generated by Django 4.1.7 on 2023-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_residence_permits', '0005_visit_place_family_residence_permit_visit_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_residence_permit',
            name='enstatus',
            field=models.CharField(choices=[('notapplied', 'Not applied'), ('applicationneeded', 'Application needed'), ('announcedrequireddocuments', 'Required documents and process were notified'), ('documentdeliverd', 'Document delivered'), ('translation', 'Translation completed'), ('notarization', 'Notarization completed'), ('applied', 'Applied'), ('waitingforinterviewdate', 'Waiting for interview date from immigration office'), ('announcedinterviewdate', 'immigration office announced interview date'), ('interviewcompleted', 'Interview completed'), ('revisitneeded', 'Revisit needed'), ('revisitcompleted', 'Revisit completed'), ('waitingforapproval', 'Waiting for approval'), ('approvedandwaitforcard', 'Approved and waiting for card'), ('carddeliveredphotoneeded', 'Card delivered, please send photos to GA team'), ('postofficevisitneeded', 'Please visit postoffice'), ('completed', 'Completed')], default='notapplied', max_length=150),
        ),
        migrations.AlterField(
            model_name='family_residence_permit',
            name='krstatus',
            field=models.CharField(choices=[('notapplied', '아직 신청하지 않음'), ('applicationneeded', '신청 필요'), ('announcedrequireddocuments', '필요서류 및 절차 공지 완료'), ('documentdeliverd', '서류 전달 완료'), ('translation', '서류 번역 완료'), ('notarization', '서류 공증 완료'), ('applied', '신청완료'), ('waitingforinterviewdate', '이민국 인터뷰 일자 공지 대기중'), ('announcedinterviewdate', '이민국 인터뷰 일자 공지 완료'), ('interviewcompleted', '이민국 인터뷰 완료'), ('revisitneeded', '다시 방문 필요'), ('revisitcompleted', '재방문 완료'), ('waitingforapproval', '승인 대기 중'), ('approvedandwaitforcard', '승인됨 카드 발급 대기 중'), ('carddeliveredphotoneeded', '카드 전달 완료됨, 총무팀에 거주증 사진 전송 필요'), ('postofficevisitneeded', '부재중으로 인해 우체국 방문 필요'), ('completed', '모든 절차 완료')], default='notapplied', max_length=150),
        ),
    ]
