# Generated by Django 4.1.7 on 2023-06-25 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driving_licenses_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('family', models.CharField(blank=True, choices=[('expat', 'Expat'), ('spouse', 'Spouse')], max_length=10)),
                ('lost_location', models.CharField(default='', max_length=180)),
                ('lost_date', models.DateField(default=datetime.date.today, verbose_name='When did you lose the card?')),
                ('revisit_date', models.DateField(default=datetime.date.today, verbose_name='Register office revisit date')),
                ('revisit_time', models.TimeField(default='19:00', verbose_name='Register office revisit time')),
                ('revisit_place', models.CharField(default='', max_length=180)),
                ('krstatus', models.CharField(choices=[('informed', '튀르키예 운전면허증을 잃어버렸어요'), ('checked', '총무팀 확인'), ('announcement_visit_schedule', '인구시민청 방문 관련 공지'), ('approvedandwaitforcard', '승인됨 카드 발급 대기 중'), ('completed', '카드 발급 및 전달 완료, 모든 절차 완료')], default='informed', max_length=100)),
                ('enstatus', models.CharField(choices=[('informed', 'I have lost card'), ('checked', 'GA team member checked the request'), ('announcement_visit_schedule', 'Visiting schedule of register office notified'), ('approvedandwaitforcard', 'Approved and waiting for car to be delivered'), ('completed', 'Completed')], default='informed', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Driving licenses requests',
            },
        ),
    ]
