# Generated by Django 4.1.7 on 2023-06-25 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driving_licenses_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driving_licenses_request',
            name='expat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_licenses_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
