# Generated by Django 4.1.7 on 2023-04-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_licenses_requests', '0002_visit_place_driving_licenses_request_visit_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driving_licenses_request',
            name='enstatus',
            field=models.CharField(choices=[('informed', 'I have lost card'), ('checked', 'GA team member checked the request'), ('announcement_visit_schedule', 'Visiting schedule of register office notified'), ('approvedandwaitforcard', 'Approved and waiting for car to be delivered'), ('completed', 'Completed')], default='informed', max_length=100),
        ),
        migrations.AlterField(
            model_name='driving_licenses_request',
            name='krstatus',
            field=models.CharField(choices=[('informed', '튀르키예 운전면허증을 잃어버렸어요'), ('checked', '총무팀 확인'), ('announcement_visit_schedule', '인구시민청 방문 관련 공지'), ('approvedandwaitforcard', '승인됨 카드 발급 대기 중'), ('completed', '카드 발급 및 전달 완료, 모든 절차 완료')], default='informed', max_length=100),
        ),
    ]
