# Generated by Django 4.1.7 on 2023-06-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Green_cards_preparation_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('contents', models.CharField(default='', max_length=5000)),
                ('signing_authority', models.CharField(default='', max_length=180)),
                ('certified_translator', models.CharField(default='', max_length=180)),
            ],
            options={
                'verbose_name_plural': 'Green card preparation documents',
            },
        ),
    ]
