# Generated by Django 4.1.7 on 2023-03-12 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Green_cards_preparation_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('contents', models.CharField(default='', max_length=5000)),
                ('signing_authority', models.CharField(default='', max_length=180)),
                ('certified_translator', models.CharField(default='', max_length=180)),
                ('expat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_cards_preparation_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
