# Generated by Django 4.1.7 on 2023-06-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('current_rent_fee', models.SmallIntegerField(default='1', verbose_name='Current rent fee')),
                ('currency_rent', models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5)),
                ('limit', models.SmallIntegerField(default='1', verbose_name='Limit')),
                ('currency_limit', models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Houses',
            },
        ),
    ]
