# Generated by Django 4.1.7 on 2023-03-12 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='expat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clause',
            name='krclause',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='clause',
            name='trclause',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
