# Generated by Django 4.1.7 on 2023-03-09 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('krstatus', models.CharField(blank=True, choices=[('notapplied', '아직 신청하지 않음'), ('applied', '신청완료'), ('waitingforapproval', '승인 대기 중'), ('approvedandwaitforcard', '승인됨 카드 발급 대기 중'), ('carddelivered', '카드 전달 완료됨'), ('completed', '모든 절차 완료')], max_length=150)),
                ('enstatus', models.CharField(blank=True, choices=[('notapplied', 'Not applied'), ('applied', 'Applied'), ('waitingforapproval', 'Waiting for approval'), ('approvedandwaitforcard', 'Approved and waiting for card'), ('carddelivered', 'Card delivered'), ('completed', 'Completed')], max_length=150)),
                ('expat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Work permits',
            },
        ),
    ]
