# Generated by Django 4.1.7 on 2023-03-07 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processes', '0002_requireddocument_alter_process_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=180)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('detailed_information', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Explanations',
            },
        ),
        migrations.RenameField(
            model_name='requireddocument',
            old_name='detailedinformation',
            new_name='detailed_information',
        ),
        migrations.RemoveField(
            model_name='process',
            name='description',
        ),
        migrations.RemoveField(
            model_name='process',
            name='detailedinformation',
        ),
        migrations.AddField(
            model_name='process',
            name='requried_documents',
            field=models.ManyToManyField(related_name='processes', to='processes.requireddocument'),
        ),
        migrations.AddField(
            model_name='process',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='explanations',
            field=models.ManyToManyField(related_name='processes', to='processes.explanation'),
        ),
    ]
