# Generated by Django 4.1.7 on 2023-03-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0003_explanation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explanation',
            old_name='title',
            new_name='name',
        ),
    ]
