# Generated by Django 4.1.7 on 2023-03-07 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0004_rename_title_explanation_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requireddocument',
            new_name='Document',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Documents'},
        ),
        migrations.RenameField(
            model_name='process',
            old_name='requried_documents',
            new_name='documents',
        ),
    ]
