# Generated by Django 4.1.7 on 2023-03-06 18:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Familyresidencepermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('turkish_id', models.SmallIntegerField(default='1', verbose_name='Turkish ID number')),
                ('tc_id_expiry_date', models.DateField(default=datetime.date.today, verbose_name='TC expiry date')),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('passport_expiry_date', models.DateField(default=datetime.date.today, verbose_name='passport expiry date')),
                ('family', models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('child1', 'CHILD1'), ('child2', 'CHILD2'), ('child3', 'CHILD3'), ('child4', 'CHILD4')], max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('expat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familyresidencepermits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
