# Generated by Django 4.1.7 on 2023-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyresidencepermits', '0002_familyresidencepermit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyresidencepermit',
            name='family',
            field=models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('child1', 'Child1'), ('child2', 'Child2'), ('child3', 'Child3'), ('child4', 'Child4')], max_length=10),
        ),
    ]
