# Generated by Django 4.1.7 on 2023-05-20 17:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0002_house_expat_alter_clause_krclause_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moving_preparation_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('spouse_name', models.CharField(default='', max_length=180)),
                ('spouse_passport', models.CharField(default='', max_length=180)),
                ('job_start_date', models.DateField(default=datetime.date.today, verbose_name='Job starting date')),
                ('job_finish_date', models.DateField(default=datetime.date.today, verbose_name='Job finish date')),
                ('contents', models.CharField(default='', max_length=5000)),
                ('signing_authority', models.CharField(default='', max_length=180)),
                ('certified_translator', models.CharField(default='', max_length=180)),
                ('ensituation', models.CharField(blank=True, choices=[('expatriation', 'Expatriation'), ('repatriation', 'Repatriation')], max_length=150)),
                ('expat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moving_preparation_documents', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moving_preparation_documents', to='houses.house')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
