# Generated by Django 4.1.7 on 2023-06-25 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moving_preparation_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('spouse_name', models.CharField(default='', max_length=180)),
                ('spouse_passport', models.CharField(default='', max_length=180)),
                ('job_start_date', models.DateField(default=datetime.date.today, verbose_name='Job starting date')),
                ('job_finish_date', models.DateField(default=datetime.date.today, verbose_name='Job finish date')),
                ('contents', models.CharField(default='', max_length=5000)),
                ('signing_authority', models.CharField(default='', max_length=180)),
                ('certified_translator', models.CharField(default='', max_length=180)),
                ('ensituation', models.CharField(blank=True, choices=[('expatriation', 'Expatriation'), ('repatriation', 'Repatriation')], max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
