# Generated by Django 4.1.7 on 2023-06-25 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moving_preparation_documents', '0001_initial'),
        ('houses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moving_preparation_document',
            name='expat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moving_preparation_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moving_preparation_document',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moving_preparation_documents', to='houses.house'),
        ),
    ]
