# Generated by Django 4.1.7 on 2023-06-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Available_country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Available countries',
            },
        ),
        migrations.CreateModel(
            name='Green_cards_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('green_card_period', models.CharField(blank=True, choices=[('fifteen_days', 'Fifteen_days'), ('one_month', 'One month'), ('three_months', 'Three months'), ('six_months', 'Six months'), ('a_year', 'A year')], max_length=50)),
                ('green_card_car_insurance_period', models.CharField(blank=True, choices=[('fifteen_days', 'Fifteen_days'), ('one_month', 'One month'), ('three_months', 'Three months'), ('six_months', 'Six months'), ('a_year', 'A year')], max_length=50)),
                ('green_card_departure_date', models.DateField(blank=True, null=True)),
                ('green_card_bank_iban_number', models.CharField(default='', max_length=180)),
                ('green_card_bank_account_name', models.CharField(default='', max_length=180)),
                ('currency_green_card', models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5)),
                ('overseas_car_insurance_bank_iban_number', models.CharField(default='', max_length=180)),
                ('overseas_car_insurance_bank_account_name', models.CharField(default='', max_length=180)),
                ('currency_overseas_car_insurance', models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5)),
                ('power_of_attorney_bank_iban_number', models.CharField(default='', max_length=180)),
                ('power_of_attorney_bank_account_name', models.CharField(default='', max_length=180)),
                ('currency_power_of_attorney', models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5)),
                ('will_you_request_green_card', models.BooleanField(default=False)),
                ('will_you_request_overseas_car_insurance', models.BooleanField(default=False)),
                ('do_you_have_power_of_attorney', models.BooleanField(default=False)),
                ('available_country', models.ManyToManyField(related_name='green_cards_requests', to='green_cards_requests.available_country')),
            ],
            options={
                'verbose_name_plural': 'Green card requests',
            },
        ),
    ]
