# Generated by Django 4.1.7 on 2023-03-12 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Green_cards_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('green_card_period', models.CharField(blank=True, choices=[('one_month', 'One month'), ('three_months', 'Three months'), ('six_months', 'Six months'), ('a_year', 'A year')], max_length=50)),
                ('green_card_car_insurance_period', models.CharField(blank=True, choices=[('one_month', 'One month'), ('three_months', 'Three months'), ('six_months', 'Six months'), ('a_year', 'A year')], max_length=50)),
                ('green_card_departure_date', models.DateField(blank=True, null=True)),
                ('will_you_request_green_card', models.BooleanField(default=False)),
                ('will_you_request_overseas_car_insurance', models.BooleanField(default=False)),
                ('do_you_have_power_of_attorney', models.BooleanField(default=False)),
                ('expat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_cards_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
