# Generated by Django 4.1.7 on 2023-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_cards_requests', '0002_available_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='green_cards_request',
            name='currency_green_card',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5),
        ),
        migrations.AddField(
            model_name='green_cards_request',
            name='currency_overseas_car_insurance',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5),
        ),
        migrations.AddField(
            model_name='green_cards_request',
            name='currency_power_of_attorney',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5),
        ),
        migrations.AddField(
            model_name='green_cards_request',
            name='green_card_bank_account_name',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='green_cards_request',
            name='green_card_bank_iban_number',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='green_cards_request',
            name='overseas_car_insurance_bank_account_name',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='green_cards_request',
            name='overseas_car_insurance_bank_iban_number',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='green_cards_request',
            name='power_of_attorney_bank_account_name',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='green_cards_request',
            name='power_of_attorney_bank_iban_number',
            field=models.CharField(default='', max_length=180),
        ),
    ]
