# Generated by Django 4.1.7 on 2023-03-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_cards_requests', '0003_green_cards_request_currency_green_card_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='green_cards_request',
            options={'verbose_name_plural': 'Green card requests'},
        ),
    ]
