# Generated by Django 4.1.7 on 2023-03-12 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0002_house_expat_alter_clause_krclause_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House_rent_extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('new_rent_fee', models.SmallIntegerField(default='1', verbose_name='new rent fee')),
                ('currency_new_rent', models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5)),
                ('limit', models.SmallIntegerField(default='1', verbose_name='Limit')),
                ('currency_limit', models.CharField(blank=True, choices=[('usd', 'USD'), ('tl', 'TL')], max_length=5)),
                ('krstatus', models.CharField(blank=True, choices=[('landlord_requested', '집주인 인상 요청'), ('negotiation', '집주인과 협상 중'), ('completed', '협상 완료')], max_length=35)),
                ('enstatus', models.CharField(blank=True, choices=[('landlord_requested', 'Landlord requested rent increase'), ('negotiation', 'Negotiation is ongoing'), ('completed', 'Negotiation is completed')], max_length=35)),
                ('expat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_rent_extensions', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_rent_extensions', to='houses.house')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
