# Generated by Django 4.1.7 on 2023-03-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_rent_extensions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house_rent_extension',
            options={'verbose_name_plural': 'House rent extensions'},
        ),
    ]
