# Generated by Django 4.1.7 on 2023-05-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_rent_extensions', '0002_alter_house_rent_extension_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house_rent_extension',
            old_name='expat',
            new_name='responsible_person',
        ),
    ]
