# Generated by Django 4.1.7 on 2023-06-26 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
        ('house_rent_extensions', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_rent_extension',
            name='house',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_rent_extensions', to='houses.house'),
        ),
    ]
