# Generated by Django 4.1.7 on 2023-04-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_cars_requests', '0002_company_cars_request_enstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_cars_request',
            name='enstatus',
            field=models.CharField(choices=[('informed', 'Informed'), ('checked', 'GA team member checked the request'), ('taking_necessary_action', 'Taking necessary action'), ('completed', 'Completed')], default='informed', max_length=100),
        ),
        migrations.AlterField(
            model_name='company_cars_request',
            name='krstatus',
            field=models.CharField(choices=[('informed', '사고가 났어요'), ('checked', '총무팀 확인'), ('taking_necessary_action', '필요한 조치 취하는 중'), ('completed', '모든 절차 완료')], default='informed', max_length=100),
        ),
    ]
