# Generated by Django 4.1.7 on 2023-06-25 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driving_licenses_preparation_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('is_english_driving_license', models.BooleanField(default=False)),
                ('krbacktype', models.CharField(blank=True, choices=[('drivers_license_test_administration', '운전면허시험관리단'), ('road_traffic_authority', '도로교통공단')], max_length=50)),
                ('trbacktype', models.CharField(blank=True, choices=[('drivers_license_test_administration', 'Ehliyet Sinavi Yönetim Kurulu'), ('road_traffic_authority', 'Trafik ve Karayollari Müdürlüğü')], max_length=50)),
                ('type', models.CharField(blank=True, choices=[('type_one', 'Type one'), ('type_two', 'Type two')], max_length=10)),
                ('changed_address', models.CharField(default='', max_length=180)),
                ('changed_date', models.DateField(default=datetime.date.today, verbose_name='When did you change address?')),
                ('two_changed_address', models.CharField(default='', max_length=180)),
                ('two_changed_date', models.DateField(default=datetime.date.today, verbose_name='When did you change address?')),
                ('three_changed_address', models.CharField(default='', max_length=180)),
                ('three_changed_date', models.DateField(default=datetime.date.today, verbose_name='When did you change address?')),
                ('driving_license_number', models.CharField(default='', max_length=180)),
                ('driving_license_type', models.CharField(default='', max_length=180)),
                ('name_surname', models.CharField(default='', max_length=180)),
                ('id_number', models.CharField(default='', max_length=180)),
                ('house_address', models.CharField(default='', max_length=700)),
                ('typeone_renewal_date', models.DateField(default=datetime.date.today, verbose_name='Type one renewal date')),
                ('typetwo_renewal_date', models.DateField(default=datetime.date.today, verbose_name='Type two renewal date')),
                ('issued_date', models.DateField(default=datetime.date.today, verbose_name='Issued date')),
                ('issued_place', models.CharField(default='', max_length=180)),
            ],
            options={
                'verbose_name_plural': 'Driving license preparation documents',
            },
        ),
    ]
