# Generated by Django 4.1.7 on 2023-03-15 19:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driving_licenses_preparation_document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('is_english_driving_license', models.BooleanField(default=False)),
                ('enbacktype', models.CharField(blank=True, choices=[('drivers_license_test_administration', "Driver's license test administration"), ('road_traffic_authority', 'Road traffic authority')], max_length=50)),
                ('krbacktype', models.CharField(blank=True, choices=[('drivers_license_test_administration', '운전면허시험관리단'), ('road_traffic_authority', '도로교통공단')], max_length=50)),
                ('trbacktype', models.CharField(blank=True, choices=[('drivers_license_test_administration', 'Ehliyet Sinavi Yönetim Kurulu'), ('road_traffic_authority', 'Trafik ve Karayollari Müdürlüğü')], max_length=50)),
                ('type', models.CharField(blank=True, choices=[('type_one', 'Type one'), ('type_two', 'Type two')], max_length=10)),
                ('changed_address', models.CharField(default='', max_length=180)),
                ('changed_date', models.DateField(default=datetime.date.today, verbose_name='When did you change address?')),
                ('driving_license_number', models.CharField(default='', max_length=180)),
                ('driving_license_type', models.CharField(default='', max_length=180)),
                ('name_surname', models.CharField(default='', max_length=180)),
                ('id_number', models.CharField(default='', max_length=180)),
                ('house_address', models.CharField(default='', max_length=700)),
                ('typeone_renewal_date', models.DateField(default=datetime.date.today, verbose_name='Type one renewal date')),
                ('typetwo_renewal_date', models.DateField(default=datetime.date.today, verbose_name='Type two renewal date')),
                ('issued_date', models.DateField(default=datetime.date.today, verbose_name='Issued date')),
                ('issued_place', models.CharField(default='', max_length=180)),
                ('expat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving_licenses_preparation_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
