# Generated by Django 4.1.7 on 2023-03-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_licenses_preparation_documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driving_licenses_preparation_document',
            options={'verbose_name_plural': 'Driving license preparation documents'},
        ),
    ]
