# Generated by Django 4.1.7 on 2023-06-26 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_licenses_preparation_documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driving_licenses_preparation_document',
            name='changed_address',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='driving_licenses_preparation_document',
            name='changed_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='When did you change address?'),
        ),
        migrations.AlterField(
            model_name='driving_licenses_preparation_document',
            name='house_address',
            field=models.CharField(blank=True, default='', max_length=700),
        ),
        migrations.AlterField(
            model_name='driving_licenses_preparation_document',
            name='three_changed_address',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='driving_licenses_preparation_document',
            name='three_changed_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='When did you change address?'),
        ),
        migrations.AlterField(
            model_name='driving_licenses_preparation_document',
            name='two_changed_address',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='driving_licenses_preparation_document',
            name='two_changed_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='When did you change address?'),
        ),
        migrations.AlterField(
            model_name='driving_licenses_preparation_document',
            name='typeone_renewal_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Type one renewal date'),
        ),
        migrations.AlterField(
            model_name='driving_licenses_preparation_document',
            name='typetwo_renewal_date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Type two renewal date'),
        ),
    ]
