# Generated by Django 4.1.7 on 2023-04-22 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_licenses_preparation_documents', '0002_alter_driving_licenses_preparation_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='driving_licenses_preparation_document',
            name='three_changed_address',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='driving_licenses_preparation_document',
            name='three_changed_date',
            field=models.DateField(default=datetime.date.today, verbose_name='When did you change address?'),
        ),
        migrations.AddField(
            model_name='driving_licenses_preparation_document',
            name='two_changed_address',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='driving_licenses_preparation_document',
            name='two_changed_date',
            field=models.DateField(default=datetime.date.today, verbose_name='When did you change address?'),
        ),
    ]
