# Generated by Django 4.1.7 on 2023-03-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_cards', '0002_explanation_alter_green_card_options_green_card_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='green_card',
            name='green_card_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='green_card',
            name='overseas_car_insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
