# Generated by Django 4.1.7 on 2023-03-12 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('green_cards', '0003_green_card_green_card_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='green_card',
            name='expat',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='green_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
