# Generated by Django 4.1.7 on 2023-03-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_request_green_card_car_insurance_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='Green_card_car_insurance_period',
            new_name='green_card_car_insurance_period',
        ),
    ]
