# Generated by Django 4.1.7 on 2023-03-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moving_companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moving_company',
            options={'verbose_name_plural': 'Moving companies'},
        ),
        migrations.AddField(
            model_name='moving_company',
            name='responsible_person_name',
            field=models.CharField(default='', max_length=180),
        ),
    ]
