# Generated by Django 4.1.7 on 2023-06-25 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family_residence_permits_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('location', models.CharField(default='', max_length=180)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='When did you lose the card?')),
                ('krstatus', models.CharField(blank=True, choices=[('informed', '거주증 카드를 잃어버렸어요'), ('checked', '총무팀 확인'), ('reapplied', '재신청 완료'), ('waitingforapproval', '승인 대기 중'), ('approvedandwaitforcard', '승인됨 카드 발급 대기 중'), ('completed', '카드 발급 및 전달 완료, 모든 절차 완료')], max_length=150)),
                ('enstatus', models.CharField(blank=True, choices=[('informed', 'Our family have lost cards'), ('checked', 'GA team member checked the request'), ('reapplied', 'Re-applied'), ('waitingforapproval', 'Waiting for approval'), ('approvedandwaitforcard', 'Approved and waiting for card'), ('completed', 'Card issued and delivered, Completed')], max_length=150)),
                ('family', models.CharField(blank=True, choices=[('spouse', 'Spouse'), ('child1', 'Child1'), ('child2', 'Child2'), ('child3', 'Child3'), ('child4', 'Child4')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Family residence permits requests',
            },
        ),
    ]
