# Generated by Django 4.1.7 on 2023-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses_supporters', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents10',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents2',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents3',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents4',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents5',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents6',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents7',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents8',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='contents9',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information10',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information2',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information3',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information4',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information5',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information6',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information7',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information8',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='detailed_information9',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle10',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle2',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle3',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle4',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle5',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle6',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle7',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle8',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='houses_supporter',
            name='subtitle9',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
    ]
