# Generated by Django 4.1.7 on 2023-06-25 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driving_license',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('expat_have_driving_license', models.BooleanField(default=False)),
                ('spouse_have_driving_license', models.BooleanField(default=False)),
                ('biometric_photo', models.BooleanField(default=False)),
                ('house_address_registration_driving_license', models.BooleanField(default=False)),
                ('notarized_driving_license', models.BooleanField(default=False)),
                ('graduation_certificate_driving_license', models.BooleanField(default=False)),
                ('health_report_driving_license', models.BooleanField(default=False)),
                ('driving_license_exchange_fee', models.BooleanField(default=False)),
                ('krstatus', models.CharField(choices=[('please_send_scanned_korean_driving_license', '스캔하신 운전면허증 앞, 뒷면을 총무팀에 보내주세요'), ('ongoing_korean_driving_license_translation', '운전면허증 번역 중'), ('completed_notarization_korean_driving_license_translation', '운전면허증 번역 공증 완료'), ('please_send_scanned_graduation_certificate', '스캔하신 졸업증명서를 총무팀에 보내주세요'), ('ongoing_graduation_certificate_translation', '졸업증명서 번역 중'), ('completed_notarization_graduation_certificate_translation', '졸업증명서 번역 공증 완료'), ('please_visit_post_office', 'e-devlet 비밀번호 발급을 위해 우체국을 방문하세요'), ('ongoing_house_address_registration', '거주증 등록 진행 중'), ('completed_house_address_registration', '거주증 등록 완료'), ('announcement_first_visit_schedule', '인구시민청 첫방문 관련 공지'), ('first_visit', '첫번째 방문'), ('please_pay_driving_license_exchange_cost', '운전면허증 교환 수수료를 납부하세요'), ('announcement_second_visit_schedule', '인구시민청 두번째방문 관련 공지'), ('second_visit', '두번째 방문'), ('revisit_needed', '재방문 필요'), ('temporary_card', '임시 운전면허증 발급'), ('approvedandwaitforcard', '승인됨 카드 발급 대기 중'), ('completed', '카드 발급 및 전달 완료, 모든 절차 완료')], default='please_send_scanned_korean_driving_license', max_length=500)),
                ('enstatus', models.CharField(choices=[('please_send_scanned_korean_driving_license', 'Please send scanned Korean driving license'), ('ongoing_korean_driving_license_translation', 'Korean driving license translation in progress'), ('completed_notarization_korean_driving_license_translation', 'Korean driving license translation has been completed and notarized'), ('please_send_scanned_graduation_certificate', 'Please send scanned graduation certificate'), ('ongoing_graduation_certificate_translation', 'Graduation certificate translation in progress'), ('completed_notarization_graduation_certificate_translation', 'Graduation certificate translation has been completed and notarized'), ('please_visit_post_office', 'Please visit post office for issuing e-devlet password'), ('ongoing_house_address_registration', 'House address registration in progress'), ('completed_house_address_registration', 'House address registration has been completed'), ('announcement_first_visit_schedule', 'Announcement of the schedule for the first visit to the registration office'), ('first_visit', 'First visit'), ('please_pay_driving_license_exchange_cost', 'Please pay driving license exchange cost'), ('announcement_second_visit_schedule', 'Announcement of the schedule for the second visit to the registration office'), ('second_visit', 'Second visit'), ('revisit_needed', 'Revisit needed'), ('temporary_card', 'Temporary card has been issued'), ('approvedandwaitforcard', 'Approved and waiting for issuing card'), ('completed', 'Card issued and sent it to you. All processes are completed.')], default='please_send_scanned_korean_driving_license', max_length=500)),
                ('family', models.CharField(blank=True, choices=[('expat', 'Expat'), ('spouse', 'Spouse')], max_length=10)),
                ('visit', models.CharField(blank=True, choices=[('first_visit', 'First visit'), ('second_visit', 'Second visit')], max_length=20)),
                ('visit_place', models.CharField(default='', max_length=180)),
                ('when_was_your_first_entry_date', models.DateField(default=datetime.date.today, verbose_name='When was your first entry date?')),
                ('visit_date', models.DateField(default=datetime.date.today, verbose_name='Visit date')),
                ('visit_time', models.TimeField(default='19:00', verbose_name='Visit time')),
            ],
            options={
                'verbose_name_plural': 'Driving licenses',
            },
        ),
    ]
