# Generated by Django 4.1.7 on 2023-03-14 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driving_license',
            name='visit',
            field=models.CharField(blank=True, choices=[('first_visit', 'First visit'), ('second_visit', 'Second visit')], max_length=20),
        ),
        migrations.AddField(
            model_name='driving_license',
            name='visit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Visit date'),
        ),
        migrations.AddField(
            model_name='driving_license',
            name='visit_place',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='driving_license',
            name='visit_time',
            field=models.TimeField(default='19:00', verbose_name='Visit time'),
        ),
    ]
