# Generated by Django 4.1.7 on 2023-03-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_licenses', '0002_driving_license_visit_driving_license_visit_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('detailed_information', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Visit places',
            },
        ),
        migrations.AddField(
            model_name='driving_license',
            name='biometric_photo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driving_license',
            name='driving_license_exchange_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driving_license',
            name='graduation_certificate_driving_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driving_license',
            name='health_report_driving_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driving_license',
            name='house_address_registration_driving_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driving_license',
            name='krstatus',
            field=models.CharField(blank=True, choices=[('please_send_scanned_korean_driving_license', '스캔하신 운전면허증 앞, 뒷면을 총무팀에 보내주세요'), ('ongoing_korean_driving_license_translation', '운전면허증 번역 중'), ('completed_notarization_korean_driving_license_translation', '운전면허증 번역 공증 완료'), ('please_send_scanned_graduation_certificate', '스캔하신 졸업증명서를 총무팀에 보내주세요'), ('ongoing_graduation_certificate_translation', '졸업증명서 번역 중'), ('completed_notarization_graduation_certificate_translation', '졸업증명서 번역 공증 완료'), ('please_visit_post_office', 'e-devlet 비밀번호 발급을 위해 우체국을 방문하세요'), ('ongoing_house_address_registration', '거주증 등록 진행 중'), ('completed_house_address_registration', '거주증 등록 완료'), ('announcement_first_visit_schedule', '인구시민청 첫방문 관련 공지'), ('first_visit', '첫번째 방문'), ('please_visit_hospital_for_health_report', '건강진단서를 위해 병원을 방문하세요'), ('please_pay_driving_license_exchange_cost', '운전면허증 교환 수수료를 납부하세요'), ('announcement_second_visit_schedule', '인구시민청 두번째방문 관련 공지'), ('second_visit', '두번째 방문'), ('revisit_needed', '재방문 필요'), ('temporary_card', '임시 운전면허증 발급'), ('approvedandwaitforcard', '승인됨 카드 발급 대기 중'), ('completed', '카드 발급 및 전달 완료, 모든 절차 완료')], max_length=100),
        ),
        migrations.AddField(
            model_name='driving_license',
            name='notarized_driving_license',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='driving_license',
            name='visit_place',
        ),
        migrations.AddField(
            model_name='driving_license',
            name='visit_place',
            field=models.ManyToManyField(related_name='driving_licenses', to='driving_licenses.visit_place'),
        ),
    ]
