# Generated by Django 4.1.7 on 2023-03-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_licenses', '0004_driving_license_when_was_your_first_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driving_license',
            options={'verbose_name_plural': 'Driving licenses'},
        ),
    ]
