# Generated by Django 4.1.7 on 2023-03-11 20:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick_ups_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('will_driver_pick_you_up_from_house', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=180)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Flight date')),
                ('time', models.TimeField(auto_now=True, verbose_name='Arrival or departure time')),
                ('driver', models.CharField(blank=True, choices=[('erhan_bey', 'Erhan bey'), ('sabri_bey', 'Sabri bey'), ('gokmen_bey', 'Gökmen bey')], max_length=10)),
                ('vehicle', models.CharField(blank=True, choices=[('h350_vip', 'H350 VIP'), ('h350_van', 'H350 VAN')], max_length=10)),
                ('krsituation', models.CharField(blank=True, choices=[('familyfirstvisit', '가족 튀르키예 첫 입국'), ('familylastexit', '가족 튀르키예 마지막 출국')], max_length=150)),
                ('ensituation', models.CharField(blank=True, choices=[('familyfirstvisit', 'family first visit'), ('familylastexit', 'family last exit')], max_length=150)),
                ('krstatus', models.CharField(blank=True, choices=[('request_submitted', '요청 제출됨'), ('checked', '총무팀 확인'), ('arranged', '드라이버, 차량 어레인지 됨')], max_length=150)),
                ('enstatus', models.CharField(blank=True, choices=[('request_submitted', 'request submitted'), ('checked', 'GA team checked the request'), ('arranged', 'Driver and vehicle arranged')], max_length=150)),
                ('expat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pick_ups_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
