# Generated by Django 4.1.7 on 2023-03-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pick_ups_requests', '0002_alter_pick_ups_request_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pick_ups_request',
            options={'verbose_name_plural': 'Pick ups requests'},
        ),
    ]
