# Generated by Django 4.1.7 on 2023-04-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_ups_requests', '0003_alter_pick_ups_request_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick_ups_request',
            name='detailed_information',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='pick_ups_request',
            name='flight_number',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='pick_ups_request',
            name='vehicle',
            field=models.CharField(blank=True, choices=[('h350_vip', 'H350 VIP'), ('h350_van', 'H350 VAN'), ('staria', 'STARIA')], max_length=10),
        ),
    ]
