# Generated by Django 4.1.7 on 2023-03-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=180)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('detailed_information', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Explanations',
            },
        ),
        migrations.AlterModelOptions(
            name='moving',
            options={'verbose_name_plural': 'Moving'},
        ),
        migrations.AddField(
            model_name='moving',
            name='name',
            field=models.CharField(default='', max_length=180),
        ),
        migrations.AddField(
            model_name='moving',
            name='explanations',
            field=models.ManyToManyField(related_name='moving', to='moving.explanation'),
        ),
    ]
